services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
