services:
  server:
    image: mobile_network_analytics:latest
    command: sh -c 'uvicorn mobile_network_analytics.api.main:app --host 0.0.0.0 --port 5000'
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - mobile_network_analytics-network
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mobile_network_analytics-network
  celery_worker:
    image: mobile_network_analytics:latest
    command: celery --app=mobile_network_analytics.celery.celery.app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    networks:
      - mobile_network_analytics-network
  celery_beat:
    image: mobile_network_analytics:latest
    command: celery -A mobile_network_analytics.celery.celery.app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    networks:
      - mobile_network_analytics-network
  redis:
    image: "redis:latest"
    networks:
      - mobile_network_analytics-network

volumes:
  mariadb_data:

networks:
  mobile_network_analytics-network:
    driver: bridge
